### ISSUE TITLE
v2.1 has crash

### ISSUE THREAD

**Issue by dundun9** [labring/endpoints-operator#115]
v2.1 crash

```
or-leader-election
E1220 06:11:26.656345       1 controller.go:190] controller-runtime/manager/controller/clusterendpoint "msg"="Could not wait for Cache to sync" "error"="failed to wait for clusterendpoint caches to sync: timed out waiting for cache to be synced" "reconciler group"="sealos.io" "reconciler kind"="ClusterEndpoint"
I1220 06:11:26.656390       1 shared_informer.go:266] stop requested
I1220 06:11:26.656439       1 reflector.go:225] Stopping reflector *v1beta1.ClusterEndpoint (9h18m46.938634076s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I1220 06:11:26.656508       1 reflector.go:225] Stopping reflector *v1.Service (9h7m52.586538365s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167
I1220 06:11:26.656514       1 shared_informer.go:266] stop requested
F1220 06:11:26.656532       1 server.go:149] unable to run the manager: failed to wait for clusterendpoint caches to sync: timed out waiting for cache to be synced
E1220 06:11:26.656574       1 internal.go:529] controller-runtime/manager "msg"="error received after stop sequence was engaged" "error"="leader election lost"
E1220 06:11:26.656589       1 internal.go:529] controller-runtime/manager "msg"="error received after stop sequence was engaged" "error"="context canceled"
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc0002bc240, 0xa4, 0x104)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x24f9f40, 0xc000000003, 0x0, 0x0, 0xc0000fb6c0, 0x1ddc08d, 0x9, 0x95, 0x0)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x24f9f40, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x18c62f6, 0x1d, 0xc0006ea2c0, 0x1, ...)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:751 +0x191
k8s.io/klog/v2.Fatalf(...)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1509
github.com/labring/endpoints-operator/cmd/endpoints-operator/app.run(0xc0001ea0f0, 0x1ac9a10, 0xc000440b80, 0xc000572000, 0x18a849f)
	/home/runner/work/endpoints-operator/endpoints-operator/cmd/endpoints-operator/app/server.go:149 +0xaec
github.com/labring/endpoints-operator/cmd/endpoints-operator/app.NewCommand.func1(0xc00051a840, 0xc000598b90, 0x0, 0x5)
	/home/runner/work/endpoints-operator/endpoints-operator/cmd/endpoints-operator/app/server.go:60 +0x50
github.com/spf13/cobra.(*Command).execute(0xc00051a840, 0xc00003a1f0, 0x5, 0x5, 0xc00051a840, 0xc00003a1f0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00051a840, 0x0, 0x162f9c0, 0xc00008c058)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/home/runner/work/endpoints-operator/endpoints-operator/cmd/endpoints-operator/endpoints-operator.go:28 +0x2a

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x24f9f40)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xdf

goroutine 32 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x24f9e60)
	/home/runner/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/home/runner/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd8

goroutine 66 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
	/opt/hostedtoolcache/go/1.16.15/x64/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/opt/hostedtoolcache/go/1.16.15/x64/src/os/signal/signal.go:151 +0x45

goroutine 44 [chan receive, 2 minutes]:
sigs.k8s.io/controller-runtime/pkg/manager/signals.SetupSignalHandler.func1(0xc000597320, 0xc000131540)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/manager/signals/signal.go:38 +0x34
created by sigs.k8s.io/controller-runtime/pkg/manager/signals.SetupSignalHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/manager/signals/signal.go:37 +0xe8

goroutine 68 [IO wait]:
internal/poll.runtime_pollWait(0x7f4f2d68afd8, 0x72, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc000142218, 0x72, 0xb900, 0xb947, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000142200, 0xc0006d6000, 0xb947, 0xb947, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000142200, 0xc0006d6000, 0xb947, 0xb947, 0xb942, 0xc0006d6000, 0x5)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0002f0140, 0xc0006d6000, 0xb947, 0xb947, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc000117ab8, 0xc0006d6000, 0xb947, 0xb947, 0xb942, 0xc000065000, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc000354cf8, 0x1a96620, 0xc000117ab8, 0x40b725, 0x16e8b40, 0x183e6a0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc000354a80, 0x1a98b80, 0xc0002f0140, 0x5, 0xc0002f0140, 0x330)
	/opt/hostedtoolcache/go/1.16.15/x64/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000354a80, 0x0, 0x0, 0x3)
	/opt/hostedtoolcache/go/1.16.15/x64/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.16.15/x64/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc000354a80, 0xc000020000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc00003b6e0, 0xc00001c2d8, 0x9, 0x9, 0x9038eb, 0xc00058dc78, 0x406fa5)
	/opt/hostedtoolcache/go/1.16.15/x64/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1a96480, 0xc00003b6e0, 0xc00001c2d8, 0x9, 0x9, 0x9, 0xc00002e1c0, 0xadddfe11a49a00, 0xc00002e1c0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/io/io.go:328 +0x87
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.16.15/x64/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader(0xc00001c2d8, 0x9, 0x9, 0x1a96480, 0xc00003b6e0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00001c2a0, 0xc00061a4e0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00058dfa8, 0x0, 0x0)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000331380)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/transport.go:705 +0x6c5

goroutine 218 [chan receive]:
k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc000514de0)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.1/util/workqueue/queue.go:204 +0xac
created by k8s.io/client-go/util/workqueue.newQueue
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.1/util/workqueue/queue.go:62 +0x154

goroutine 143 [chan send]:
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).serveHealthProbes(0xc00000a1e0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/manager/internal.go:432 +0x15a
created by sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).Start
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/manager/internal.go:477 +0x445

goroutine 221 [chan send]:
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1(0xc00016ec90, 0x1ac9a10, 0xc000295b00, 0x1adbf10, 0xc0004c9840, 0x1aca030, 0x2529530, 0xc000131030, 0x1, 0x1)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/source/source.go:131 +0x15f
created by sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/source/source.go:122 +0x152

goroutine 222 [chan send]:
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1(0xc00016eba0, 0x1ac9a10, 0xc000295d00, 0x1adbf10, 0xc0004c9840, 0x1aca068, 0xc000119e50, 0xc000131210, 0x1, 0x1)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/source/source.go:137 +0x3f6
created by sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/source/source.go:122 +0x152

```

**Comment by cuisongliu** [comment]
```
unable to run the manager: failed to wait for clusterendpoint caches to sync: timed out waiting for cache to be synced
```

same timeout for synced cache

**Comment by mytting** [comment]
Using an earlier version (the one that just added hosts in port) doesn't have this problem.

**Comment by cuisongliu** [comment]
没有复现
